# compose.yaml

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent overwriting node_modules in container
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data # Mount host folder for data persistence
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env

volumes:
  db_data:
